### ISSUE TITLE
Dicom processing

### ISSUE THREAD

**Issue by Robylyon93** [nyukat/breast_density_classifier#5]
Hi, since mammograms are stored by default in .dcm files, I would like to know what kind of preprocessing has been done (if any) while converting from dicoms to png.

Thanks a lot.

**Comment by kjgeras** [comment]
We did not do any preprocessing to the dicom images. Just loaded them into a numpy array, cropped the center and saved them as png. In this code, before using them, we are normalising them to have zero mean and unit variance.
