### ISSUE TITLE
Inference / Training on less than 4 views

### ISSUE THREAD

**Issue by Linardos** [nyukat/breast_density_classifier#7]
I wanted to do some experiments with the DDSM dataset using your code but your neural network seems to expect four inputs per patient corresponding to left / right + cc / mlo. In some patients of DDSM unfortunately not all views are present. Some have 2 some 3 some have all 4. 
Not sure why that's the case with DDSM, It's a pretty 'dirty' dataset in many respects though so I'm not surprised. 
Is there a way to use your model on patients that don't have all 4 views?

**Comment by kjgeras** [comment]
Hi Akis,

I think the easiest thing which is a little wrong but also pretty easy, would be to duplicate one of the available views (probably doesn't matter which one) so that there are 4 views in total. I expect that this should work reasonably well.

**Comment by Linardos** [comment]
Hmm I see. That was my first thought as well. I guess It wouldn't hurt to try. I'll probably make some comparative analysis later on using just the 4 view samples and see whether adding the incomplete samples severely impacts performance.
Thank you so much for making this open source and well documented by the way!

**Comment by Linardos** [comment]
One more question regarding this if I may: We have received some feedback that there asymmetries between breasts occur so that the left's density is different to the right's which is indicative of cancer / cause for alarm. It seems this information is lost if we concatenate them.
Was it a radiologist's recommendation to use 4 different views towards a single density classification or is there some practical reason for it?

**Comment by kjgeras** [comment]
This is how radiologists report it (at least at NYU). The entire exam has only one label characterizing breast density.

**Comment by Linardos** [comment]
That's really useful to know, thanks!
